[package]
name = "day5_tokio_streams"
version = "0.1.0"
edition = "2024"

[dependencies]
async-stream = "0.3.6"
gcp_auth = "0.12.3"
reqwest = { version = "0.12.22", features = ["stream"] }
tokio = { version = "1.47.1", features = ["full"] }
tokio-stream = "0.1.17"
